src/Entity/Answer.php
<?php

namespace App\Entity;

use App\Enum\AnswerStatus;
use App\Repository\AnswerRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;

#[ORM\Entity(repositoryClass: AnswerRepository::class)]
class Answer
{
    private AnswerStatus $statusCases;

    use TimestampableEntity;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $content = null;

    #[ORM\Column(length: 255)]
    private ?string $username = null;

    #[ORM\Column]
    private int $votes = 0;

    #[ORM\ManyToOne(inversedBy: 'answers')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Question $question = null;

    #[ORM\Column(length: 15)]
    private ?string $status;

    public function __construct()
    {
        $this->status = AnswerStatus::NEEDS_APPROVAL->value;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): static
    {
        $this->content = $content;

        return $this;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): static
    {
        $this->username = $username;

        return $this;
    }

    public function getVotes(): int
    {
        return $this->votes;
    }

    public function setVotes(int $votes): static
    {
        $this->votes = $votes;

        return $this;
    }

    public function getQuestion(): ?Question
    {
        return $this->question;
    }

    public function getQuestionText(): string
    {
        if (!$this->getQuestion()) {
            return '';
        }

        return (string)$this->question->getQuestion();
    }

    public function setQuestion(?Question $question): static
    {
        $this->question = $question;

        return $this;
    }

    public function upVote(): self
    {
        $this->votes++;

        return $this;
    }

    public function downVote(): self
    {
        $this->votes--;

        return $this;
    }

    public function getStatus(): ?AnswerStatus
    {
        return AnswerStatus::tryFrom($this->status);
    }

    public function setStatus(?string $status): static
    {
        $availableStatuses = array_column(AnswerStatus::cases(), 'value');

        if (!in_array($status, $availableStatuses)) {
            throw new \InvalidArgumentException(sprintf("Invalid status '%s'", $status));
        }

        $this->status = $status;

        return $this;
    }
}

src/Controller/AnswerController.php
<?php

namespace App\Controller;

use App\Entity\Answer;
use App\Repository\AnswerRepository;
use App\Service\VotingService;
use Psr\Log\LoggerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

class AnswerController extends AbstractController
{
    #[Route('/answers/{id}/vote', name: 'answer_vote', methods: "POST")]
    #[IsGranted('IS_AUTHENTICATED_REMEMBERED')]
    public function answerVote(Request $request, Answer $answer, VotingService $votingService, LoggerInterface $logger): Response
    {
//        $logger->info("{user} is voting on answer {answer}", ['user' => $this->getUser()->getUserIdentifier(), 'answer' => $answer->getId()]);
//        dd($this->getUser());

        $data = json_decode($request->getContent(), true);

        $votingService->vote($answer, $data['direction']);

        return $this->json(['votes' => $answer->getVotes()]);
    }

    #[Route(path: "/answers/popular", name: "app_popular_answers", methods: "GET")]
    public function popularAnswers(AnswerRepository $answerRepository, Request $request)
    {
        $answers = $answerRepository->findMostPopular($request->query->get('q'));

        return $this->render('answer/popular_answer.html.twig', ['answers' => $answers]);
    }
}

templates/answer/_answer.html.twig
<li class="mb-4">
    {% if showQuestion|default(false) %}
        <a href="{{ path('questions.show', { slug: answer.question.slug }) }}"
           class="mb-1 link-secondary">
            <strong>Question</strong>
            {{ answer.questionText|u.truncate(80, '...') }}
        </a>
    {% endif %}
    <div class="d-flex justify-content-center gap-3">
        <div class="mr-2 pt-2">
            <img src="{{ asset('images/tisha.png') }}" width="50" height="50" alt="Mallory Avatar">
        </div>
        <div class="mr-3 pt-2">
            {#                                                        {{ answer|striptags|markdown }} #}
            {{ answer.content|parse_markdown }}
            {#                            {{ answer.status|dd }} #}
            <p>-- {{ answer.username }}</p>
        </div>
        <div class="col-2 text-end">
            <small>
                {{ answer.createdAt|ago }}
            </small>
            {% if is_granted('IS_AUTHENTICATED_REMEMBERED') %}
                <div
                    class="vote-arrows"
                    {{ stimulus_controller('answer-vote', {
                        url: path('answer_vote', {
                            id: answer.id
                        })
                    }) }}
                >

                    <button
                        class="vote-up btn btn-link"
                        name="direction"
                        value="up"
                        {{ stimulus_action('answer-vote', 'clickVote') }}
                    ><i class="far fa-arrow-alt-circle-up"></i></button>
                    <button
                        class="vote-down btn btn-link"
                        name="direction"
                        value="down"
                        {{ stimulus_action('answer-vote', 'clickVote') }}
                    ><i class="far fa-arrow-alt-circle-down"></i></button>

                    <span>+ <span {{ stimulus_target('answer-vote', 'voteTotal') }}>{{ answer.votes }}</span></span>
                </div>
            {% endif %}
        </div>
    </div>
</li>

templates/answer/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello AnswerController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'D:/www/learningSymfony/src/Controller/AnswerController.php'|file_link(0) }}">src/Controller/AnswerController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'D:/www/learningSymfony/templates/answer/index.html.twig'|file_link(0) }}">templates/answer/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/answer/popular_answer.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Popular Answer
{% endblock %}


{% block body %}
    <div class="container my-md-4">
        <div class="d-flex justify-content-between">
            <h1>Most Popular Answers</h1>

            <form action="{{ path('app_popular_answers') }}">
                <input
                    type="search"
                    name="q"
                    value="{{ app.request.query.get('q') }}"
                    class="form-control"
                    placeholder="Search..."
                    aria-label="Search"
                >
            </form>
        </div>

        <ul class="list-unstyled">
            {% for answer in answers %}
                {{ include('answer/_answer.html.twig', {
                    showQuestion: true
                }) }}
            {% endfor %}
        </ul>
    </div>
{% endblock %}