src/Entity/Question.php
<?php

namespace App\Entity;

use App\Enum\AnswerStatus;
use App\Repository\AnswerRepository;
use App\Repository\QuestionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\Criteria;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation\Slug;
use Gedmo\Timestampable\Traits\TimestampableEntity;

#[ORM\Entity(repositoryClass: QuestionRepository::class)]
class Question
{
    use TimestampableEntity;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 100, unique: true)]
    #[Slug(fields: ['name'])]
    private ?string $slug = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $question = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTime $askedAt = null;

    #[ORM\Column]
    private ?int $votes = 0;

    #[ORM\OneToMany(mappedBy: 'question', targetEntity: Answer::class, fetch: 'EXTRA_LAZY')]
    #[ORM\OrderBy(['createdAt' => 'desc'])]
    private Collection $answers;

    #[ORM\OneToMany(mappedBy: 'question', targetEntity: QuestionTag::class)]
    private Collection $questionTags;

    #[ORM\ManyToOne(inversedBy: 'questions')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $owner = null;

    public function __construct()
    {
        $this->answers = new ArrayCollection();
        $this->questionTags = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }

    public function getQuestion(): ?string
    {
        return $this->question;
    }

    public function setQuestion(string $question): static
    {
        $this->question = $question;

        return $this;
    }

    public function getAskedAt(): ?\DateTime
    {
        return $this->askedAt;
    }

    public function setAskedAt(?\DateTime $askedAt): static
    {
        $this->askedAt = $askedAt;

        return $this;
    }

    public function getVotes(): int
    {
        return $this->votes;
    }

    public function getVotesString(): string
    {
        $prefix = $this->votes >= 0 ? '+' : '-';

        return sprintf('%s %d', $prefix, abs($this->votes));
    }

    public function setVotes(int $votes): static
    {
        $this->votes = $votes;

        return $this;
    }

    public function upVote(): self
    {
        $this->votes++;

        return $this;
    }

    public function downVote(): self
    {
        $this->votes--;

        return $this;
    }

    /**
     * @return Collection<int, Answer>
     */
    public function getAnswers(): Collection
    {
        return $this->answers;
    }

    public function getApprovedAnswers(): Collection
    {
//        return $this->answers->filter(fn(Answer $answer) => $answer->getStatus()?->isApproved());

        return $this->answers->matching(AnswerRepository::createApprovedCriteria());
    }

    public function addAnswer(Answer $answer): static
    {
        if (!$this->answers->contains($answer)) {
            $this->answers->add($answer);
            $answer->setQuestion($this);
        }

        return $this;
    }

    public function removeAnswer(Answer $answer): static
    {
        if ($this->answers->removeElement($answer)) {
            // set the owning side to null (unless already changed)
            if ($answer->getQuestion() === $this) {
                $answer->setQuestion(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, QuestionTag>
     */
    public function getQuestionTags(): Collection
    {
        return $this->questionTags;
    }

    public function addQuestionTag(QuestionTag $questionTag): static
    {
        if (!$this->questionTags->contains($questionTag)) {
            $this->questionTags->add($questionTag);
            $questionTag->setQuestion($this);
        }

        return $this;
    }

    public function removeQuestionTag(QuestionTag $questionTag): static
    {
        if ($this->questionTags->removeElement($questionTag)) {
            // set the owning side to null (unless already changed)
            if ($questionTag->getQuestion() === $this) {
                $questionTag->setQuestion(null);
            }
        }

        return $this;
    }

    public function getOwner(): ?User
    {
        return $this->owner;
    }

    public function setOwner(?User $owner): static
    {
        $this->owner = $owner;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Scheb\TwoFactorBundle\Model\Totp\TotpConfiguration;
use Scheb\TwoFactorBundle\Model\Totp\TotpConfigurationInterface;
use Scheb\TwoFactorBundle\Model\Totp\TwoFactorInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Serializer\Annotation\Groups;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface, TwoFactorInterface
{
    use TimestampableEntity;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups('user:read')]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    #[Groups(['user:read'])]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups('user:read')]
    private ?string $firstName;

    #[ORM\Column(length: 255)]
    private ?string $password = null;

    private ?string $plainPassword = null;

    #[ORM\OneToMany(mappedBy: 'owner', targetEntity: Question::class)]
    private Collection $questions;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $verifiedAt = null;

    #[ORM\Column(type:"string", length:255, nullable: true)]
    private ?string $totpSecret;

    public function __construct()
    {
        $this->questions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string)$this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        $this->plainPassword = null;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): static
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getPlainPassword(): ?string
    {
        return $this->plainPassword;
    }

    /**
     * @param string|null $plainPassword
     */
    public function setPlainPassword(?string $plainPassword): static
    {
        $this->plainPassword = $plainPassword;

        return $this;
    }

    #[Groups(['user:read'])]
    public function getAvatarUri(int $size = 32): string
    {
        return "https://ui-avatars.com/api/?" . http_build_query([
                'name' => $this->getDisplayName(),
                'size' => $size,
                'background' => 'random'
            ]);
    }

    public function getDisplayName(): string
    {
        return $this->firstName ?: $this->email;
    }

    /**
     * @return Collection<int, Question>
     */
    public function getQuestions(): Collection
    {
        return $this->questions;
    }

    public function addQuestion(Question $question): static
    {
        if (!$this->questions->contains($question)) {
            $this->questions->add($question);
            $question->setOwner($this);
        }

        return $this;
    }

    public function removeQuestion(Question $question): static
    {
        if ($this->questions->removeElement($question)) {
            // set the owning side to null (unless already changed)
            if ($question->getOwner() === $this) {
                $question->setOwner(null);
            }
        }

        return $this;
    }

    public function getVerifiedAt(): ?\DateTimeImmutable
    {
        return $this->verifiedAt;
    }

    public function setVerifiedAt(?\DateTimeImmutable $verifiedAt): static
    {
        $this->verifiedAt = $verifiedAt;

        return $this;
    }

    public function setTotpSecret(?string $totpSecret): self
    {
        $this->totpSecret = $totpSecret;
        return $this;
    }

    public function isTotpAuthenticationEnabled(): bool
    {
        return (bool)$this->totpSecret;
    }

    public function getTotpAuthenticationUsername(): string
    {
        return $this->getUserIdentifier();
    }

    public function getTotpAuthenticationConfiguration(): ?TotpConfigurationInterface
    {
        return new TotpConfiguration($this->totpSecret, TotpConfiguration::ALGORITHM_SHA1, 30, 6);
    }
}

src/Controller/QuestionController.php
<?php

namespace App\Controller;

use App\Entity\Question;
use App\Repository\AnswerRepository;
use App\Repository\QuestionRepository;
use App\Service\VotingService;
use Doctrine\ORM\EntityManagerInterface;
use Pagerfanta\Doctrine\ORM\QueryAdapter;
use Pagerfanta\Pagerfanta;
use Psr\Log\LoggerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Finder\Exception\AccessDeniedException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use Twig\Environment;

// fourth way: (globally on all controller routes)
//#[IsGranted('ROLE_ADMIN')] // Can use role name or IS_AUTHENTICATED_FULLY
class QuestionController extends BaseController
{
    public function __construct(private LoggerInterface $logger, private bool $isDebug, private EntityManagerInterface $entityManager)
    {

    }

    /**
     * @Route("/{page<\d+>}", name="questions.index")
     */
    public function homepage(Environment $twigEnvironment, QuestionRepository $questionRepository, int $page = 1)
    {
        /*
        $html = $twigEnvironment->render('question/homepage.html.twig');

        return new Response(($html));
        */
        $queryBuilder = $questionRepository->createAskedOrderedByNewestQueryBuilder();

        $pagerfanta = new Pagerfanta(
            new QueryAdapter($queryBuilder)
        );

        $pagerfanta->setMaxPerPage(5);
        $pagerfanta->setCurrentPage($page);

        // Same as:
        return $this->render('question/homepage.html.twig', [
            'pager' => $pagerfanta
        ]);
    }

    #[Route('/questions/new', name: "questions.new")]
    // Third way:
    #[IsGranted("ROLE_USER")] // Can use role name or IS_AUTHENTICATED_FULLY
    public function new(): Response
    {
        // Adding access to role
        // first way:
//        $this->denyAccessUnlessGranted('ROLE_ADMIN'); // Can use role name or IS_AUTHENTICATED_FULLY
        // second way:
//        if (!$this->isGranted('ROLE_ADMIN')) { // Can use role name or IS_AUTHENTICATED_FULLY
//            throw $this->createAccessDeniedException('No access for you!');
//        }

        return new Response('Sounds like a GREAT feature for V2!');
    }

    #[Route('/questions/{slug}', name: 'questions.show')]
    public function show(Question $question, AnswerRepository $answerRepository): Response
    {
        if ($this->isDebug) {
            $this->logger->info('We are in debug mode');
        }

//        $answers = $answerRepository->findBy([
//            'question' => $question
//        ]);
        // OR
//        $answers = $question->getAnswers();
//        dd($question->getApprovedAnswers());
        return $this->render('question/show.html.twig', [
            'question' => $question,
        ]);
    }

    #[Route('/questions/edit/{slug}', name: 'app_question_edit')]
//    #[IsGranted('IS_AUTHENTICATED_REMEMBERED')]
    public function edit(Question $question, QuestionRepository $questionRepository, AnswerRepository $answerRepository): Response
    {
//        if ($question->getOwner() !== $this->getUser()) {
//            throw $this->createAccessDeniedException('You are not the owner!');
//        }

        $this->denyAccessUnlessGranted('EDIT', $question);

        return $this->render('question/edit.html.twig', [
            'question' => $question,
        ]);
    }

    /**
     * @Route("/questions/{slug}/vote", name="questions.vote", methods="POST")
     */
    public function questionVote(Question $question, Request $request, VotingService $votingService)
    {
        $votingService->vote($question, $request->get('direction'));

        $user = $this->getUser();
        return $this->redirectToRoute('questions.show', ['slug' => $question->getSlug()]);
    }
}

templates/question/edit.html.twig
{% extends 'base.html.twig' %}
{% block title %}Edit Question: {{ question.name }}{% endblock %}
{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h1 class="my-4">Edit Question</h1>
                <blockquote>{{ question.question }}</blockquote>
                TODO
            </div>
        </div>
    </div>
{% endblock %}

templates/question/homepage.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="jumbotron-img jumbotron jumbotron-fluid">
        <div class="container">
            <h1 class="display-4">Your Questions Answered</h1>
            <p class="lead">And even answers for those questions you didn't think to ask!</p>
        </div>
    </div>
    <div class="container">
        <div class="row mb-3">
            <div class="col">
                <button class="btn btn-question">Ask a Question</button>
            </div>
        </div>
        <div class="row">
            {% for question in pager %}
                <div class="col-12">
                    <div style="box-shadow: 2px 3px 9px 4px rgba(0,0,0,0.04);">
                        <div class="q-container p-4">
                            <div class="row">
                                <div class="col-2 text-center">
                                    <img src="{{ question.owner.avatarUri }}" width="100" height="100" alt="{{ question.owner.displayName }}">
                                    <div class="d-block mt-3 vote-arrows">
                                        <a class="vote-up"
                                           href="{{ path('comments.vote', { id: question.id, direction: 'up' }) }}"><i
                                                class="far fa-arrow-alt-circle-up"></i></a>
                                        <a class="vote-down"
                                           href="{{ path('comments.vote', { id: question.id, direction: 'down' }) }}"><i
                                                class="far fa-arrow-alt-circle-down"></i></a>
                                    </div>

                                    {% for questionTag in question.questionTags %}
                                        <span class="badge rounded-pill bg-light text-dark">{{ questionTag.tag.name }}</span>
                                    {% endfor %}
                                </div>
                                <div class="col">
                                    <a class="q-title"
                                       href="{{ path('questions.show', { slug: question.slug }) }}"><h2>{{ question.name }}</h2></a>
                                    <div class="q-display p-3">
                                        <i class="fa fa-quote-left mr-3"></i>
                                        <p class="d-inline">{{ question.question|parse_markdown }}</p>
                                        <p class="pt-4"><strong>--{{ question.owner.displayName }}</strong></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <a class="answer-link" href="{{ path('questions.show', { slug: question.slug }) }}"
                           style="color: #fff;">
                            <p class="q-display-response text-center p-3">
                                <i class="fa fa-magic magic-wand"></i> {{ question.approvedAnswers|length }} answers
                            </p>
                        </a>
                    </div>
                </div>
            {% endfor %}

            {{ pagerfanta(pager) }}
        </div>
    </div>
{% endblock %}

templates/question/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Question: {{ question.name }}{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h2 class="my-4">Question</h2>
                <div style="box-shadow: 2px 3px 9px 4px rgba(0,0,0,0.04);">
                    <div class="q-container-show p-4">
                        <div class="row">
                            <div class="col-2 text-center">
                                <img src="{{ question.owner.avatarUri }}" width="100" height="100"
                                     alt="{{ question.owner.displayName }}">
                                <div class="mt-4">
                                    <small>
                                        {% if question.askedAt %}
                                            Asked <br>
                                            {#                                            {{ question.getAskedAt|carbonParse.diffForHumans }} #}
                                            {#                                            {{ carbonParse(question.askedAt).diffForHumans }} #}
                                            {{ carbonParse(question.askedAt)|ago }}
                                        {% endif %}
                                    </small>

                                    <div class="vote-arrows vote-arrows-alt flex-fill pt-2" style="min-width: 90px;">
                                        <form action="{{ path('questions.vote', {slug: question.slug}) }}"
                                              method="POST">
                                            <button class="vote-up btn btn-link" name="direction" value="up"
                                                    style="font-size: 1.3rem"><i class="far fa-arrow-alt-circle-up"></i>
                                            </button>
                                            <button class="vote-down btn btn-link" name="direction" value="down"
                                                    style="font-size: 1.3rem"><i
                                                    class="far fa-arrow-alt-circle-down"></i></button>
                                        </form>
                                        <span>
                                            {{ question.votesString }}
                                        </span>
                                    </div>
                                </div>
                            </div>
                            <div class="col">
                                <div class="d-flex justify-content-between">
                                    <h1 class="q-title-show">{{ question.name }}</h1>
                                    {% if is_granted('EDIT', question) %}
                                        <a href="{{ path('app_question_edit', {'slug': question.slug}) }}"
                                           class="btn btn-secondary btn-sm mb-2">Edit</a>
                                    {% endif %}
                                </div>
                                <div class="q-display p-3">
                                    <i class="fa fa-quote-left mr-3"></i>
                                    <p class="d-inline">{{ question.question|parse_markdown }}</p>
                                    <p class="pt-4"><strong>--{{ question.owner.displayName }}</strong></p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="d-flex justify-content-between my-4">
            <h2 class="">Answers <span style="font-size:1.2rem;">({{ question.approvedAnswers|length }})</span></h2>
            <button class="btn btn-sm btn-secondary">Submit an Answer</button>
        </div>


        <ul class="list-unstyled">
            {% for answer in question.approvedAnswers %}
                {{ include('answer/_answer.html.twig') }}
            {% endfor %}
        </ul>
    </div>
{% endblock %}