src/Entity/ImagePost.php
<?php

namespace App\Entity;

use App\Repository\ImagePostRepository;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;

#[ORM\Entity(repositoryClass: ImagePostRepository::class)]
class ImagePost
{
    use TimestampableEntity;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $filename = null;

    #[ORM\Column(length: 255)]
    private ?string $originalFilename = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $ponkaAddedAt = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFilename(): ?string
    {
        return $this->filename;
    }

    public function setFilename(string $filename): static
    {
        $this->filename = $filename;

        return $this;
    }

    public function getOriginalFilename(): ?string
    {
        return $this->originalFilename;
    }

    public function setOriginalFilename(string $originalFilename): static
    {
        $this->originalFilename = $originalFilename;

        return $this;
    }

    public function getPonkaAddedAt(): ?\DateTimeImmutable
    {
        return $this->ponkaAddedAt;
    }

    public function markAsPonkaAdded(): static
    {
        $this->ponkaAddedAt = new \DateTimeImmutable();

        return $this;
    }

    public function getImageFullPath(): string
    {
        return 'uploads/images/' . $this->filename;
    }
}

src/Controller/MainController.php
<?php

namespace App\Controller;

use App\Repository\ImagePostRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class MainController extends AbstractController
{
    #[Route('/', name: 'app_main_homepage')]
    public function homepage(ImagePostRepository $imagePostRepository)
    {
        $images = $imagePostRepository->findBy([], ['createdAt' => 'DESC']);

        return $this->render('main/homepage.html.twig', [
            'images' => $images
        ]);
    }
}

templates/main/homepage.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-6">
                <form method="POST" action="{{ path('upload_image') }}" enctype="multipart/form-data">
                    <label for="imageFile">Choose an image file:</label>
                    <input type="file" id="file" name="file[]" class="btn btn-dark mt-3" multiple="multiple" accept="image/*" required>
                    <br>
                    <input type="submit" class="btn btn-primary mt-3" value="Upload">
                </form>
            </div>
            <div class="col-6">
                <div class="">
                    {% for image in images %}
                        <div class="col-12">

                            <div class="p-4">
                                <div class="d-flex justify-content-evenly">
                                    <img src="{{ asset(image.imageFullPath) }}" width="100" height="100"
                                         alt="{{ image.filename }}">
                                    <form method="POST" action="{{ path('app_imagepost_delete', { id: image.id }) }}">
                                        <input type="hidden" name="_csrf_token"
                                               value="{{ csrf_token('authenticate') }}"
                                        >
                                        <input type="hidden" name="_method" value="DELETE">
                                        <button class="btn btn-danger" type="submit">X</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}